### ISSUE TITLE
Ignore element

### ISSUE THREAD

**Issue by rushenn** [boblauer/react-onclickout#8]
Hi,

Thank you for this cool component. It would be so nice if you can implement an option to ignore certain elements when clicking outside. 

Regards.

**Comment by captbaritone** [comment]
A nice way to implement this might be to allow the user to specify a filter function which gets passed the event. Then the user can check for classes, node types or compare with actual references to known nodes.

**Comment by boblauer** [comment]
That's a good suggestion.  What do you think about this approach?

```js
excludeClickedOutElement(event) {
  return hasClass(event.target, 'exclude-me');
}

render() {
  <OnClickOut exclude={this.excludeClickedOutElement} ...>
}
```

I'm thinking `exclude` instead of `filter` so that you can return `true` to ignore the element, where as the term `filter` could be kind of confusing here (am I keeping elements I want to ignore, or filtering them out?)

Thoughts?

**Comment by captbaritone** [comment]
Maybe `ignoreEvents`?

**Comment by ianstormtaylor** [comment]
Hey @boblauer, btw thanks for the great clean and simple lib.

Since we already have access to the event in `onClickOut`, so why not just put the logic there? That would keep it just as streamlined as it currently is:

```js
onClickOut = (e) => {
  if (hasClass(event.target, 'exclude-me')) return
  ...
}
```

I might be missing something!

**Comment by ianstormtaylor** [comment]
@boblauer yup, just to keep things simple.

**Comment by boblauer** [comment]
Yeah, that's a great idea.  I'll update the README to include a section on that.  Thanks for the suggestion.
