### ISSUE TITLE
Optional useCapture for addEventListener

### ISSUE THREAD

**Issue by maullerz** [boblauer/react-onclickout#9]
Hello!
With useCapture param we can use stopPropagation() and prevent event from bubling on above elements.

**Comment by maullerz** [comment]
this PR was incorrect - #10
but what another way can we propose to implement such behavior?

**Comment by boblauer** [comment]
What is the exact behavior that you are trying to achieve?

**Comment by maullerz** [comment]
I have some table with search panel on top. When clicked on search panel modal form appeared, and i want to close that form when click out of it.
And i want to stop propagation of click-event to prevent clicking on elements laying under.

**Comment by boblauer** [comment]
And are you sure the click event triggers on the elements underneath?  I don't think they should, because by the time the `onClickOut` handler is called, the event has bubbled all the way up to the `window`

**Comment by maullerz** [comment]
Yes i am sure, cause bubbling going through that controls before window event handler executes (window is last).

**Comment by boblauer** [comment]
Thanks for the screenshot, that helps.

How about adding a transparent overlay behind the modal, to prevent anything else from being clicked?

**Comment by maullerz** [comment]
Yes exactly this way i have used for workaround.

**Comment by boblauer** [comment]
I'm not quite sure how I would go about implementing it.  The way the event system is currently set up, I don't see how I could prevent the onclick event from happening outside of the modal.

Closing for now, as a transparent overlay seems to be the best approach for the time being.
